version: '3.9'

services:
  server:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
  db:
    image: 'postgis/postgis'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: